# Generated by Django 5.0.1 on 2025-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, help_text="Payment terms (e.g., 'Net 30', '2/10 Net 30', 'Due on Receipt')", max_length=50, null=True),
        ),
    ]
