# Generated by Django 5.2.1 on 2025-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
