#!/bin/bash

echo "🚀 Invoice Processing App Deployment Helper"
echo "==========================================="
echo ""

echo "This script will guide you through deploying your app:"
echo "• Backend (FastAPI) → Railway"
echo "• Frontend (Next.js) → Vercel"
echo ""

echo "📋 Pre-deployment checklist:"
echo "• ✅ Code is committed to GitHub"
echo "• ✅ You have Railway and Vercel accounts"
echo "• ✅ You have your API keys ready"
echo ""

echo "🔧 Environment Variables Needed:"
echo ""
echo "For Railway (Backend):"
echo "• ANTHROPIC_API_KEY=your_anthropic_key"
echo "• AWS_DEFAULT_REGION=us-east-1"
echo "• AWS_ACCESS_KEY_ID=your_aws_key"
echo "• AWS_SECRET_ACCESS_KEY=your_aws_secret"
echo "• FRONTEND_URL=https://your-app.vercel.app"
echo ""
echo "For Vercel (Frontend):"
echo "• PYTHON_API_URL=https://your-backend.railway.app"
echo ""

echo "📖 Next Steps:"
echo "1. Deploy backend to Railway first"
echo "2. Copy the Railway URL"
echo "3. Deploy frontend to Vercel with Railway URL"
echo "4. Update Railway with Vercel URL"
echo ""
echo "📚 See DEPLOYMENT.md for detailed instructions"
echo ""
echo "🌐 Useful Links:"
echo "• Railway: https://railway.app"
echo "• Vercel: https://vercel.com"
echo "" 