[build]
cmd = "pip install -r backend/requirements.txt"

[start]
cmd = "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn invoice_backend.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.build]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
] 