# Generated by Django 5.1.6 on 2025-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
