# Generated by Django 5.2.1 on 2025-06-17 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_assigned_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name for this rule', max_length=100)),
                ('rule', models.TextField(help_text='Natural language description of when this rule applies')),
                ('function_assignees', models.CharField(choices=[('IT', 'Information Technology'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('Procurement', 'Procurement'), ('Warehouse', 'Warehouse')], help_text='Department/function to assign to', max_length=20)),
                ('user_ruleset', models.CharField(choices=[('round_robin', 'Round Robin'), ('user_priority', 'User Priority'), ('random', 'Random'), ('least_assigned', 'Least Assigned')], default='round_robin', help_text='Method for selecting user within the function', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('priority', models.IntegerField(default=100, help_text='Rule priority (lower numbers = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRuleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Priority within this rule (lower numbers = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_users', to='invoices.assignmentrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'unique_together': {('assignment_rule', 'user')},
            },
        ),
    ]
