# Generated by Django 5.2.1 on 2025-06-17 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_assignmentrule_assignmentruleuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignment_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
