# Generated by Django 5.2.1 on 2025-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review', 'Review'), ('pending_approval', 'Pending Approval'), ('in_approval', 'In Approval'), ('approved', 'Approved'), ('escalated', 'Escalated'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
