# Generated by Django 5.0.1 on 2025-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedinvoice',
            name='currency_code',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='due_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlineitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
