# Generated by Django 5.1.6 on 2025-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_extraction', '0002_alter_extractedinvoice_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoice',
            name='billing_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinvoice',
            name='payment_term_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
