# Generated by Django 5.1.6 on 2025-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_extraction', '0003_extractedinvoice_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
