# Generated by Django 5.0.1 on 2025-06-02 06:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('overall_status', models.CharField(choices=[('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('REJECTED', 'Rejected')], default='PARTIAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='invoices.company')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='purchase_orders.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received', to='invoices.vendor')),
            ],
            options={
                'verbose_name': 'Goods Received',
                'verbose_name_plural': 'Goods Received',
                'ordering': ['-date', '-gr_number'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_status', models.CharField(choices=[('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('REJECTED', 'Rejected')], default='PARTIAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='goods_received.goodsreceived')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.item')),
            ],
            options={
                'unique_together': {('goods_received', 'item')},
            },
        ),
    ]
